language: ruby
cache: bundler
branches:
  only:
  - gh-pages
  - /.*/
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
matrix:
  allow_failures:
    - rvm: 2.3.4
    - rvm: 2.4.1
  fast_finish: true
install:
  - travis_retry bundle install
script:
  - rake test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
