locale                   : "da"
title                    : "larsolesen.dk"
title_separator          : "-"
name                     : "larsolesen.dk"
description              : "larsolesen.dk."
url                      : "" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "lsolesen/larsolesen-dk-jekyll" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
