backend:
  name: github
  repo: lsolesen/larsolesen-dk-jekyll
  branch: gh-pages # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    label_singular: "Post"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "list", allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", allow_add: false}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - label: Header
        name: header
        widget: object
        required: false
        fields:
          - {label: Overlay color, name: overlay_color, widget: string, required: false}
          - {label: Overlay image, name: overlay_image, widget: string, required: false}
          - {label: Teaser image, name: teaser, widget: string, required: false}
          - {label: Caption, name: caption, widget: string, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Show TOC", name: "toc", widget: "select", options: ["true", "false"], default: false, required: false}
      - label: Sidebar
        name: sidebar
        widget: object
        required: false
        fields:
          - {label: Sidebar Navigation, name: nav, widget: string, required: false}
  - name: "global_settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "_data/navigation.yml"
        name: "main-navigation"
        label: "Main navigation"
        description: "Main navigation"
        format: yaml
        extension: yml
        fields:
          - label: "Links"
            name: main
            widget: list
            required: false
            fields:
              - {label: Url, name: title, widget: string}
              - {label: Url, name: url, widget: string}
      - file: "_data/settings.yml"
        name: "global_settings"
        label: "settings"
        format: yaml
        extension: yml  
        description: "Global settings"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Name, name: name, widget: string}
      - file: "_data/site_author.yml"
        name: "author"
        format: yaml
        extension: yml
        label: "Site Author"
        description: "Settings about the global site author"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Bio", name: "bio", widget: "string"}
          - {label: "Location", name: "location", widget: "string"}
          - label: "Links"
            name: links
            widget: list
            required: false
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Url, name: url, widget: string}
